version: '3'
services:
  # Consul server on "VM"
  consul:
    image: consul:1.6.1
    command: ["consul","agent","-config-file=/etc/consul.d/server.hcl"]
    volumes:
      - "./consul_config:/etc/consul.d/config"
    ports:
      - 8600
      - 8502
      - 8500:8500
      - 8302
      - 8301
      - 8300
    networks:
      onprem:
        ipv4_address: 10.5.0.2
      wan:
        ipv4_address: 192.169.7.2

  # Nomad server on "VM"
  nomad:
    image: nomad-vm
    privileged: true
    ports:
      - 4647
      - 4646:4646
    networks:
      dc1:
        ipv4_address: 10.5.0.3
      wan:
        ipv4_address: 192.169.7.3

networks:
  dc1:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
  wan:
    driver: bridge
    ipam:
     config:
       - subnet: 192.169.7.0/24